### ISSUE TITLE
Confusion between pretrained: str and pretrained: bool

### ISSUE THREAD

**Issue by hassiahk** [Quick-AI/quickvision#42]
## 🚀 Feature
Can we change the `pretrained: str` that we currently have like below to `pretrained_weights: str`? 
https://github.com/Quick-AI/quickvision/blob/c1dbb6ea4ad0ef8fac09dc2faae2740d4ba2e24a/quickvision/models/components/torchvision_backbones.py#L51 https://github.com/Quick-AI/quickvision/blob/c1dbb6ea4ad0ef8fac09dc2faae2740d4ba2e24a/quickvision/pretrained/_pretrained_weights.py#L6

Because, most of them will get confused between `pretrained: str` and `pretrained: bool` until and unless they read the docs, even I got confused at first. And since we want to make it more `torch` friendly, it would be great if we can change this.

I know it will be a lot of work if we change it now for the whole codebase, so probably we can do this afterwards and keep in mind to change it whenever we come across. But I personally feel, it would be great if we can have it now.

**Comment by oke-aditya** [comment]
Hi @hassiahk 

The 2nd function is a `_` function which isn't enabled to end user through init etc. So the only way to access pretrained is code 1.

In this library we do something opposite to torchvision. We always use pretrained as `str` not a bool

**Comment by hassiahk** [comment]
I am fine with it @oke-aditya. I said this because we want to make this library as close to `torch` as possible.

**Comment by oke-aditya** [comment]
Yes. But limiting pretrained to `True` only will limit the API.
Currently because of this rename we can load other weights on any dataset. we can use `pretrained="imagenet"`, `pretrained="instagram"`, to load weights from any dataset people would like.

Just have your model weights as `"model_name" : url` in `_pretrained_weights.py` file for models and it would be possible.
This allows people to bring their own pretrained weights on datasets they like !


The other alternative that was possible is allow user to take `pretrained=False` and the load state dict manually.
That would cause errors on their side if these werent' supported.

**Comment by hassiahk** [comment]
Now, I get it. That really makes sense and thanks for clarifying it :smile:
