### ISSUE TITLE
Support all Torchvision Models

### ISSUE THREAD

**Issue by SauravMaheshkar** [Quick-AI/quickvision#72]
## 🚀 Feature
Add pre-trained weights for most torchvision models WideResnet from torchhub

### Motivation
Adds to the library of pre-trained weights

- [x] WideResnet
- [ ] DenseNet

### Pitch

- [x] Add WideResnet weights from [here](https://pytorch.org/hub/pytorch_vision_wide_resnet/) to the model_zoo
- [ ] Simliarly add DenseNet

**Comment by oke-aditya** [comment]
It's easier to include this in torchvision model zoo, since this is from pytorch/vision.
I had thoughts about other `torch.hub` possible weights. Let me make this issue a bit generic.

Though there are small problems of our support with torchvision weights (E.g. we wrap it around `nn.Sequential`) object and we don't currently support layer freezing, unfreezing, etc. Let's think about it in seperate issue.
